"""test

Revision ID: 2302411d81a3
Revises: 1fd0cec495e4
Create Date: 2019-03-31 12:07:11.861000

"""

# revision identifiers, used by Alembic.
revision = '2302411d81a3'
down_revision = '1fd0cec495e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
